M48
; DRILL file {KiCad (6.0.11-0)} date Monday, March 27, 2023 at 04:27:20 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-03-27T16:27:20-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.230
%
G90
G05
T1
X53.42Y-45.84
X53.42Y-134.58
X147.4Y-45.68
X147.4Y-134.62
T2
X97.155Y-73.025
T3
X149.9Y-66.04
X149.9Y-96.48
T0
M30
